name: Build Cherry Studio (external)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Clone Cherry Studio
        run: |
          git clone https://github.com/CherryHQ/cherry-studio.git

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Apply patches
        working-directory: cherry-studio
        run: git apply --ignore-space-change --ignore-whitespace ../patches/cherry-studio/0001-Patch-Cherry-Studio.patch

      - name: Install dependencies
        working-directory: cherry-studio
        run: pnpm i

      - name: Download custom electron@37.2.2
        run: curl -L https://github.com/e3kskoy7wqk/Electron-for-windows-7/releases/download/v37.2.2/dist.zip -o dist.zip

      - name: Unzip custom electron
        shell: pwsh
        run: Expand-Archive dist.zip -DestinationPath dist

      - name: Replace electron with custom version
        shell: cmd
        run: |
          set electronPath=cherry-studio\node_modules\electron\dist
          if exist %electronPath% rmdir /s /q "%electronPath%"
          move dist cherry-studio\node_modules\electron\dist

      - name: Add dist to electron-shutdown-handler
        run: robocopy sources\electron-shutdown-handler\dist cherry-studio\node_modules\@get-wrecked\electron-shutdown-handler\dist /E
        continue-on-error: true

      - name: Build Cherry Studio
        working-directory: cherry-studio
        run: pnpm build:win:x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cherry-studio-build
          path: cherry-studio/dist/win-unpacked/*.exe
